import os
import json
from dotenv import load_dotenv
from google import genai
from google.genai import types

# Load variables from your secure local .env shield
load_dotenv()

def run_ad_group_architect():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY is missing from your .env file.")
        return

    # 1. Read the keywords.json file generated by Module A
    input_file_path = "output/keywords.json"
    if not os.path.exists(input_file_path):
        print(f"ERROR: Could not find input file at {input_file_path}. Please run keyword_synthesizer.py first.")
        return

    with open(input_file_path, "r") as f:
        keyword_data = json.load(f)

    print("Initializing Google Gen AI Production Client...")
    client = genai.Client()

    # 2. Craft our Module B system guidelines framework for Google Ads compliance
    system_instruction = (
        "You are an expert Google Ads copywriter. Your task is to process a structured JSON map of keywords "
        "and generate distinct, highly optimized Ad Groups with responsive search ad (RSA) copy.\n\n"
        "CRITICAL GOOGLE ADS RESTRAINTS:\n"
        "- Headlines MUST be 30 characters or fewer.\n"
        "- Descriptions MUST be 90 characters or fewer.\n"
        "- Create exactly two Ad Groups: 'Purchase_Intent_Group' and 'Service_Intent_Group'.\n"
        "- For each group, provide 3 unique Headlines and 2 unique Descriptions matching those specific keywords."
    )

    user_prompt = f"Analyze this keyword dataset and generate the ad copy framework:\n{json.dumps(keyword_data)}"

    print("Transmitting keyword payload to Gemini for Ad Group generation...")
    
    # 3. Instruct Gemini to output a strict machine-readable Ad Copy layout
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.2,
            response_mime_type="application/json",
            response_schema={
                "type": "OBJECT",
                "properties": {
                    "ad_groups": {
                        "type": "ARRAY",
                        "items": {
                            "type": "OBJECT",
                            "properties": {
                                "ad_group_name": {"type": "STRING"},
                                "target_keywords": {"type": "ARRAY", "items": {"type": "STRING"}},
                                "headlines": {
                                    "type": "ARRAY", 
                                    "items": {"type": "STRING"},
                                    "description": "Exactly 3 headlines. Max 30 chars each."
                                },
                                "descriptions": {
                                    "type": "ARRAY", 
                                    "items": {"type": "STRING"},
                                    "description": "Exactly 2 descriptions. Max 90 chars each."
                                }
                            },
                            "required": ["ad_group_name", "target_keywords", "headlines", "descriptions"]
                        }
                    }
                },
                "required": ["ad_groups"]
            }
        )
    )

    print("\n--- GENERATED AD GROUP JSON MATRIX ---")
    print(response.text)
    print("---------------------------------------")

    # 4. Save the finalized ad configuration into your 'output' directory
    try:
        json_data = json.loads(response.text)
        output_file_path = "output/ad_groups.json"
        with open(output_file_path, "w") as f:
            json.dump(json_data, f, indent=4)
        print(f"SUCCESS: Campaign architecture safely cached inside {output_file_path}!")
    except Exception as e:
        print(f"Failed to cache Ad Group JSON: {e}")

if __name__ == "__main__":
    run_ad_group_architect()